version: "3.8"

services:
  app:
    build:
      context: ./php-fpm
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

volumes:
  postgres-data:
